warner:
  host: "127.0.0.1"
  port: 8086
  measurement:
    login:
      -
        day: "1-7"
        time: "00:00-24:00"
        text: The count of successful login is abnormal
        where:
          - result = success
        start: "-5m"
        func:
          - count(account)
        check: count > 100
      -
        day: ["1", "2", "3", "4", "5", "6", "7"]
        time: ["00:00-12:00", "12:00-24:00"]
        text: The count of failed login is abnormal
        where:
          - result = fail
        func:
          - count(account)
        check: count < 10
      -
        text: The count of failed login(group by account's type) is abnormal
        group: type
        where:
          - result = fail
        func:
          - count(account)
        check: count < 1 
