sudo: false
language: node_js
node_js:
  - "8"
  - "7"
  - "6"

services:
  - docker

before_install:
  - docker pull influxdb:alpine
  - docker run -d -p 8086:8086 influxdb:alpine

script:
  - npm test

after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
